/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedBookingsRouteImport } from './routes/_authenticated/bookings'
import { Route as AuthenticatedCommunityRouteImport } from './routes/_authenticated/community'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedListMachineryRouteImport } from './routes/_authenticated/list-machinery'
import { Route as AuthenticatedListingsRouteImport } from './routes/_authenticated/listings'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedResiduesRouteImport } from './routes/_authenticated/residues'
import { Route as AuthenticatedVoiceRouteImport } from './routes/_authenticated/voice'
import { Route as AuthenticatedMachineryIndexRouteImport } from './routes/_authenticated/machinery.index'
import { Route as AuthenticatedMachineryIdRouteImport } from './routes/_authenticated/machinery.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBookingsRoute = AuthenticatedBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCommunityRoute = AuthenticatedCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedListMachineryRoute =
  AuthenticatedListMachineryRouteImport.update({
    id: '/list-machinery',
    path: '/list-machinery',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedListingsRoute = AuthenticatedListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedResiduesRoute = AuthenticatedResiduesRouteImport.update({
  id: '/residues',
  path: '/residues',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVoiceRoute = AuthenticatedVoiceRouteImport.update({
  id: '/voice',
  path: '/voice',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMachineryIndexRoute =
  AuthenticatedMachineryIndexRouteImport.update({
    id: '/machinery/',
    path: '/machinery/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMachineryIdRoute =
  AuthenticatedMachineryIdRouteImport.update({
    id: '/machinery/$id',
    path: '/machinery/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bookings': typeof AuthenticatedBookingsRoute
  '/community': typeof AuthenticatedCommunityRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/list-machinery': typeof AuthenticatedListMachineryRoute
  '/listings': typeof AuthenticatedListingsRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/residues': typeof AuthenticatedResiduesRoute
  '/voice': typeof AuthenticatedVoiceRoute
  '/machinery/$id': typeof AuthenticatedMachineryIdRoute
  '/machinery/': typeof AuthenticatedMachineryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bookings': typeof AuthenticatedBookingsRoute
  '/community': typeof AuthenticatedCommunityRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/list-machinery': typeof AuthenticatedListMachineryRoute
  '/listings': typeof AuthenticatedListingsRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/residues': typeof AuthenticatedResiduesRoute
  '/voice': typeof AuthenticatedVoiceRoute
  '/machinery/$id': typeof AuthenticatedMachineryIdRoute
  '/machinery': typeof AuthenticatedMachineryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/bookings': typeof AuthenticatedBookingsRoute
  '/_authenticated/community': typeof AuthenticatedCommunityRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/list-machinery': typeof AuthenticatedListMachineryRoute
  '/_authenticated/listings': typeof AuthenticatedListingsRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/residues': typeof AuthenticatedResiduesRoute
  '/_authenticated/voice': typeof AuthenticatedVoiceRoute
  '/_authenticated/machinery/$id': typeof AuthenticatedMachineryIdRoute
  '/_authenticated/machinery/': typeof AuthenticatedMachineryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/bookings'
    | '/community'
    | '/dashboard'
    | '/list-machinery'
    | '/listings'
    | '/notifications'
    | '/profile'
    | '/residues'
    | '/voice'
    | '/machinery/$id'
    | '/machinery/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/bookings'
    | '/community'
    | '/dashboard'
    | '/list-machinery'
    | '/listings'
    | '/notifications'
    | '/profile'
    | '/residues'
    | '/voice'
    | '/machinery/$id'
    | '/machinery'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/bookings'
    | '/_authenticated/community'
    | '/_authenticated/dashboard'
    | '/_authenticated/list-machinery'
    | '/_authenticated/listings'
    | '/_authenticated/notifications'
    | '/_authenticated/profile'
    | '/_authenticated/residues'
    | '/_authenticated/voice'
    | '/_authenticated/machinery/$id'
    | '/_authenticated/machinery/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/bookings': {
      id: '/_authenticated/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof AuthenticatedBookingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/community': {
      id: '/_authenticated/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof AuthenticatedCommunityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/list-machinery': {
      id: '/_authenticated/list-machinery'
      path: '/list-machinery'
      fullPath: '/list-machinery'
      preLoaderRoute: typeof AuthenticatedListMachineryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/listings': {
      id: '/_authenticated/listings'
      path: '/listings'
      fullPath: '/listings'
      preLoaderRoute: typeof AuthenticatedListingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/residues': {
      id: '/_authenticated/residues'
      path: '/residues'
      fullPath: '/residues'
      preLoaderRoute: typeof AuthenticatedResiduesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/voice': {
      id: '/_authenticated/voice'
      path: '/voice'
      fullPath: '/voice'
      preLoaderRoute: typeof AuthenticatedVoiceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/machinery/': {
      id: '/_authenticated/machinery/'
      path: '/machinery'
      fullPath: '/machinery/'
      preLoaderRoute: typeof AuthenticatedMachineryIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/machinery/$id': {
      id: '/_authenticated/machinery/$id'
      path: '/machinery/$id'
      fullPath: '/machinery/$id'
      preLoaderRoute: typeof AuthenticatedMachineryIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBookingsRoute: typeof AuthenticatedBookingsRoute
  AuthenticatedCommunityRoute: typeof AuthenticatedCommunityRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedListMachineryRoute: typeof AuthenticatedListMachineryRoute
  AuthenticatedListingsRoute: typeof AuthenticatedListingsRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedResiduesRoute: typeof AuthenticatedResiduesRoute
  AuthenticatedVoiceRoute: typeof AuthenticatedVoiceRoute
  AuthenticatedMachineryIdRoute: typeof AuthenticatedMachineryIdRoute
  AuthenticatedMachineryIndexRoute: typeof AuthenticatedMachineryIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBookingsRoute: AuthenticatedBookingsRoute,
  AuthenticatedCommunityRoute: AuthenticatedCommunityRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedListMachineryRoute: AuthenticatedListMachineryRoute,
  AuthenticatedListingsRoute: AuthenticatedListingsRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedResiduesRoute: AuthenticatedResiduesRoute,
  AuthenticatedVoiceRoute: AuthenticatedVoiceRoute,
  AuthenticatedMachineryIdRoute: AuthenticatedMachineryIdRoute,
  AuthenticatedMachineryIndexRoute: AuthenticatedMachineryIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
