/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedListMachineryRouteImport } from './routes/_authenticated/list-machinery'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedMachineryIndexRouteImport } from './routes/_authenticated/machinery.index'
import { Route as AuthenticatedMachineryIdRouteImport } from './routes/_authenticated/machinery.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedListMachineryRoute =
  AuthenticatedListMachineryRouteImport.update({
    id: '/list-machinery',
    path: '/list-machinery',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMachineryIndexRoute =
  AuthenticatedMachineryIndexRouteImport.update({
    id: '/machinery/',
    path: '/machinery/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMachineryIdRoute =
  AuthenticatedMachineryIdRouteImport.update({
    id: '/machinery/$id',
    path: '/machinery/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/list-machinery': typeof AuthenticatedListMachineryRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/machinery/$id': typeof AuthenticatedMachineryIdRoute
  '/machinery/': typeof AuthenticatedMachineryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/list-machinery': typeof AuthenticatedListMachineryRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/machinery/$id': typeof AuthenticatedMachineryIdRoute
  '/machinery': typeof AuthenticatedMachineryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/list-machinery': typeof AuthenticatedListMachineryRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/machinery/$id': typeof AuthenticatedMachineryIdRoute
  '/_authenticated/machinery/': typeof AuthenticatedMachineryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/list-machinery'
    | '/profile'
    | '/machinery/$id'
    | '/machinery/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/list-machinery'
    | '/profile'
    | '/machinery/$id'
    | '/machinery'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/list-machinery'
    | '/_authenticated/profile'
    | '/_authenticated/machinery/$id'
    | '/_authenticated/machinery/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/list-machinery': {
      id: '/_authenticated/list-machinery'
      path: '/list-machinery'
      fullPath: '/list-machinery'
      preLoaderRoute: typeof AuthenticatedListMachineryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/machinery/': {
      id: '/_authenticated/machinery/'
      path: '/machinery'
      fullPath: '/machinery/'
      preLoaderRoute: typeof AuthenticatedMachineryIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/machinery/$id': {
      id: '/_authenticated/machinery/$id'
      path: '/machinery/$id'
      fullPath: '/machinery/$id'
      preLoaderRoute: typeof AuthenticatedMachineryIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedListMachineryRoute: typeof AuthenticatedListMachineryRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedMachineryIdRoute: typeof AuthenticatedMachineryIdRoute
  AuthenticatedMachineryIndexRoute: typeof AuthenticatedMachineryIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedListMachineryRoute: AuthenticatedListMachineryRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedMachineryIdRoute: AuthenticatedMachineryIdRoute,
  AuthenticatedMachineryIndexRoute: AuthenticatedMachineryIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
